$body = @{
  docs = @(
    @{ content = "La Inteligencia Artificial es el conjunto de tecnicas que permiten a las maquinas aprender a partir de datos, reconocer patrones y tomar decisiones o hacer predicciones. La IA esta transformando rapidamente la vida y los negocios, mejorando diagnosticos medicos, agricultura, manufactura, finanzas y transporte. Un sistema simple de IA es un sistema con la capacidad de aprender."; source = "Clase_1_IA.txt" },
    @{ content = "Clasificacion de la Inteligencia Artificial: Artificial Superintelligence (ASI) es la IA sustancialmente mas alla de la inteligencia humana. Artificial General Intelligence (AGI) busca construir sistemas inteligentes de proposito general comparables con la gama de tareas humanas. Artificial Narrow Intelligence (ANI) imita aspectos angostos de la inteligencia humana, como vision artificial, reconocimiento de voz y procesamiento del lenguaje natural."; source = "Clase_1_IA.txt" },
    @{ content = "Tipos de IA segun memoria: Purely Reactive no tiene memoria y reacciona a lo que ve, ejemplo AlphaGo. Limited Memory incorpora fragmentos de experiencias pasadas para tomar decisiones, ejemplo Siri. Theory of Mind entiende pensamientos y emociones. Self Aware son conscientes de su estado interno."; source = "Clase_1_IA.txt" },
    @{ content = "Diferencias clave entre IA, ML y DL: Inteligencia Artificial es el campo general que busca crear sistemas inteligentes. Machine Learning es un subcampo de la IA donde los modelos aprenden a partir de datos. Deep Learning es un subcampo de ML basado en redes neuronales profundas, ideal para imagenes, texto y audio."; source = "Clase_1_IA.txt" },
    @{ content = "Breve historia de la IA: Anos 50-80 IA simbolica y reglas. Anos 90-2000 ML clasico. 2010-hoy Big Data mas Deep Learning. Areas de aplicacion: Salud, Finanzas, Retail, Gobierno, Industria, Educacion, Desarrollo de software. Riesgos: sesgo en datos, privacidad, alucinaciones en modelos generativos, falta de explicabilidad, dependencia excesiva de automatizacion."; source = "Clase_1_IA.txt" },
    @{ content = "Pipeline general de Machine Learning ciclo de vida: 1. Definicion del problema. 2. Recoleccion y preparacion de datos. 3. Entrenamiento del modelo. 4. Evaluacion del modelo. 5. Despliegue y monitoreo. Un proyecto de IA es un proceso continuo, no un script aislado. El 80 por ciento del trabajo en IA es data: limpieza, transformacion, analisis y validacion."; source = "Clase_1_IA.txt" },
    @{ content = "Tipos de problemas en Machine Learning: Clasificacion produce resultado discreto, ejemplo spam o no spam, fraude o no fraude. Regresion produce resultado numerico, ejemplo precio, demanda, temperatura. Clustering es agrupacion sin etiquetas, ejemplo segmentacion de clientes."; source = "Clase_1_IA.txt" },
    @{ content = "El rol del desarrollador de IA: entender el problema del negocio, traducirlo a un problema de ML, integrar modelos en aplicaciones reales, evaluar rendimiento costos y riesgos, mantener y monitorear modelos en produccion. IA no vive sola, vive dentro de sistemas. Del prototipo al producto."; source = "Clase_1_IA.txt" },
    @{ content = "Numpy es una libreria fundamental para la computacion cientifica con Python. Proporciona arrays N-dimensionales, implementa funciones matematicas sofisticadas, herramientas para integrar C/C++ y Fortran, y mecanismos para algebra lineal y numeros aleatorios."; source = "Librerias_ML.txt" },
    @{ content = "Pandas es una libreria que proporciona estructuras de datos y herramientas de analisis de datos de alto rendimiento. La estructura principal es el DataFrame, una tabla 2D en memoria. Permite crear tablas dinamicas, calcular columnas, trazar graficos, y manipular grandes conjuntos de datos con alto rendimiento."; source = "Librerias_ML.txt" },
    @{ content = "Matplotlib es una libreria para la creacion de figuras y graficos de calidad mediante Python. Permite la creacion de graficos de manera sencilla y eficiente, y la integracion de graficos en Jupyter Notebook."; source = "Librerias_ML.txt" },
    @{ content = "Scikit-learn es una libreria de aprendizaje automatico de codigo abierto que soporta aprendizaje supervisado y no supervisado. Proporciona herramientas para entrenamiento de modelos, preprocesamiento de datos, seleccion y evaluacion de modelos. Es simple y eficiente, construido sobre Numpy y Matplotlib, codigo libre Open Source."; source = "Librerias_ML.txt" },
    @{ content = "TensorFlow es una libreria con ecosistema integral y flexible de herramientas para ML. Permite crear y desplegar facilmente aplicaciones basadas en ML. Proporciona mas flexibilidad que Scikit-learn, permite implementacion de redes neuronales artificiales, integracion sencilla con GPU, codigo abierto Open Source."; source = "Librerias_ML.txt" },
    @{ content = "Keras es una libreria de redes neuronales de alto nivel escrita en Python que se ejecuta sobre TensorFlow. Permite experimentacion rapida, implementacion rapida y sencilla de redes neuronales artificiales, soporte transparente de CPU y GPU, codigo abierto Open Source."; source = "Librerias_ML.txt" },
    @{ content = "Machine Learning es un subcampo de la IA que proporciona a los sistemas la capacidad de aprender y mejorar automaticamente a partir de la experiencia sin ser programados explicitamente. Se basa en crear el modelo y mejorarlo ajustando mas datos a lo largo del tiempo. No todos los problemas en IA pueden solucionarse con ML, el problema debe poder solucionarse con datos."; source = "Intro_ML.txt" },
    @{ content = "Cuando utilizar Machine Learning: en soluciones con extenso conjunto de reglas o heuristicas, en problemas complejos donde un analista no puede determinar solucion, en entornos que fluctuan frecuentemente, y cuando se tienen conjuntos de datos muy grandes y dificiles de interpretar."; source = "Intro_ML.txt" },
    @{ content = "Clasificacion de sistemas de ML segun entrenamiento: Aprendizaje supervisado, no supervisado, semi-supervisado y reforzado. Segun tiempo: aprendizaje online y batch. Segun predicciones: basado en instancias y basado en modelos."; source = "Intro_ML.txt" },
    @{ content = "Aprendizaje supervisado es la tarea de aprender una funcion que mapea una entrada a una salida basada en pares de entrada-salida de ejemplo. Dos tipos: Regresion intenta predecir valores continuos, Clasificacion intenta predecir valores discretos."; source = "Intro_ML.txt" },
    @{ content = "Aprendizaje no supervisado infiere una funcion que describe la estructura de un conjunto de datos sin etiquetar, datos no clasificados ni categorizados. Aprendizaje batch no aprende de manera incremental, se entrena con todos los datos disponibles. Aprendizaje online se entrena incrementalmente mediante consumo incremental de datos individuales o mini-batches."; source = "Intro_ML.txt" },
    @{ content = "Redes Neuronales Artificiales RNA son el componente principal del Deep Learning. Se introducen en 1943 por Warren McCulloch y Walter Pitts. En 1990s pierden interes a favor de SVM. En 2012 el Deep Learning resurge cuando Geoffrey Hinton gana ImageNet con una Red Neuronal Convolucional."; source = "Redes_Neuronales.txt" },
    @{ content = "Por que resurgen las RNA: gran cantidad de datos disponibles, poder computacional multiplicado permitiendo algoritmos complejos, mejora de algoritmos RNA, y limitaciones teoricas resultaron ser benignas en practica."; source = "Redes_Neuronales.txt" },
    @{ content = "El Perceptron es una de las arquitecturas RNA mas sencillas, inventado en 1957 por Frank Rosenblatt. Se basa en Threshold Logic Unit TLU. La TLU computa una suma parametrizada de entradas y aplica una funcion de activacion. Funciones de activacion comunes: Heaviside step function y Sign function."; source = "Redes_Neuronales.txt" },
    @{ content = "Limitaciones del Perceptron: no proporciona probabilidad sino threshold estatico, construye limites de decision lineales, no permite resolver problemas como XOR. Las limitaciones se solucionan con Multi-Layer Perceptron MLP agregando mas capas de TLUs."; source = "Redes_Neuronales.txt" },
    @{ content = "Tipos de redes neuronales: Perceptron Multicapa MLP tiene capas ocultas entre input y output. Redes fully connected donde cada neurona se conecta con todas las de la capa siguiente. Redes Neuronales Convolucionales CNN usan convolucion y max-pooling, ideales para imagenes. Redes Neuronales Recurrentes RNN procesan secuencias: one to one, one to many, many to one, many to many."; source = "Redes_Neuronales.txt" }
  )
} | ConvertTo-Json -Depth 3

Invoke-RestMethod -Uri "http://localhost:3000/api/ingestion/batch" -Method POST -ContentType "application/json" -Body $body
Write-Host "Documentos indexados exitosamente!"